(()=>{'use strict';
const K={p:'rc.plan2',l:'rc.log2',f:'rc.pref2',w:'rc.waves1'},$=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],J=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??d}catch{return d}},E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const P=[
['stop','STOP — não agir no automático','dbt','DBT/TCD · crise',70,'Crie espaço entre urgência e ação.',['Pare. Não envie, responda ou decida ainda.','Perceba os pontos de apoio do corpo.','Observe: o que sinto, penso e quero fazer?','Escolha só o próximo passo seguro e reversível.'],'Se a situação exige atenção física imediata, priorize a segurança e não use a tela.'],
['adiar','Adiar decisão importante','dbt','DBT/TCD · crise',75,'Separe o problema real da urgência de resolvê-lo agora.',['Diga: “Posso reavaliar isso depois.”','Liste o que não precisa ser decidido agora.','Escolha uma ação neutra e reversível.','Defina um momento posterior para reavaliar.'],'Adie apenas o que pode esperar; urgências reais exigem avaliação adequada.'],
['exalar','Expiração suavemente mais longa','corpo','Corpo · desacelerar',90,'Respire sem retenção e deixe a saída do ar um pouco mais longa.',['Solte os ombros e note a respiração.','Inspire leve por 4 tempos.','Expire confortável por 6 tempos.','Repita sem forçar.','Volte à respiração espontânea e olhe ao redor.'],'Se houver tontura, falta de ar ou piora, pare e respire normalmente.'],
['orientar','Orientação pelos sentidos','corpo','Corpo · presente',105,'Use visão, tato e audição para voltar ao ambiente atual.',['Olhe três objetos e note suas cores.','Perceba três pontos de contato do corpo.','Identifique três sons.','Observe um objeto neutro.','Pergunte: qual é o próximo passo pequeno e seguro?'],'Mantenha os olhos abertos se fechá-los aumentar desconforto.'],
['pressao','Pressão e apoio corporal','corpo','Corpo · apoio',70,'Torne o apoio físico mais nítido.',['Apoie os pés e perceba a pressão.','Pressione levemente os pés e solte.','Una as palmas das mãos e solte.','Perceba costas, quadris ou braços sendo sustentados.'],'Não use força que cause dor.'],
['movimento','Movimento pequeno e orientado','corpo','Corpo · reconectar',95,'Use movimento gradual quando houver peso ou distanciamento.',['Mova lentamente os dedos.','Pressione os pés no chão.','Gire os ombros no confortável.','Olhe para os lados e encontre algo familiar.','Escolha uma ação simples: água, postura ou proximidade.'],'Evite movimentos rápidos se houver tontura, fraqueza ou dor.'],
['temperatura','Temperatura confortável','corpo','Corpo · sensorial',65,'Use um estímulo térmico suave, nunca extremo.',['Segure um objeto fresco ou morno.','Nomeie a sensação: fresco, neutro ou morno.','Troque de mão.','Olhe ao redor e nomeie onde está.'],'Não use gelo direto, calor intenso ou algo que cause dor.'],
['onda','Observar a urgência como uma onda','dbt','DBT/TCD · tolerância',105,'Note que a urgência muda e não precisa virar ação.',['Onde a urgência aparece no corpo?','Dê uma nota mental de intensidade.','Perceba se cresce, diminui ou muda.','Diga: “Uma urgência não é uma ordem.”','Escolha não agir por mais alguns minutos.'],'Se olhar para dentro piorar muito, volte aos sentidos ou procure apoio humano.'],
['desfusao','Nomear sem discutir com a mente','act','ACT · desfusão',80,'Veja pensamentos como pensamentos, não como ordens.',['Note: “Minha mente está dizendo que preciso resolver isso agora.”','Acrescente: “Estou percebendo esse pensamento.”','Deixe a sensação existir sem virar decisão.','Pergunte qual ação segura escolheria sem obedecer ao pensamento.'],'Se soar invalidante, reconheça primeiro: “Isso está difícil agora.”'],
['valores','Próxima ação guiada por valores','act','ACT · valores',85,'Escolha uma ação pequena na direção do que importa.',['O que importa proteger agora?','Escolha um valor: segurança, respeito, vínculo, saúde, trabalho ou descanso.','Qual é a menor ação segura nessa direção?','Faça só a ação pequena; o restante pode esperar.'],'Valores são direção, não cobrança.'],
['conexao','Conexão segura','conexao','Conexão · apoio',75,'Organize um contato humano simples e previsível.',['Pense em alguém seguro e respeitoso.','Formule: “Você pode ficar comigo alguns minutos?”','Escolha presença, ligação ou mensagem.','Faça apenas o próximo contato.'],'Se alguém aumenta medo, pressão ou conflito, escolha outro apoio.'],
['sabia','Mente sábia: emoção + fatos + valores','dbt','DBT/TCD · integração',95,'Integre emoção, fatos observáveis e direção pessoal.',['O que minha emoção tenta proteger?','Quais fatos observáveis tenho?','O que ainda é interpretação ou previsão?','O que quero proteger na forma como ajo?','Escolha a resposta mais simples que integre isso.'],'Use quando houver alguma estabilidade; no pico prefira STOP ou orientação.']
].map(x=>({id:x[0],title:x[1],framework:x[2],label:x[3],duration:x[4],desc:x[5],steps:x[6].map((t,i)=>[t,i===x[6].length-1?20:Math.max(12,Math.floor(x[4]/x[6].length))]),safety:x[7],intro:x[5]}));
let st=null,a=null,t=null,el=0,si=0,se=0,bi=5,bc=5,voice=false,install=null;
const T=s=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;
function toast(x){let e=$('#toast');e.textContent=x;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2200)}
function route(r){$$('.view').forEach(v=>v.classList.toggle('active',v.dataset.view===r));$$('.nav-item').forEach(b=>{let q=b.dataset.route===r;b.classList.toggle('active',q);q?b.setAttribute('aria-current','page'):b.removeAttribute('aria-current')});scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});if(r==='mapa')log();if(r==='depois')waves()}
function prefs(){let p=J(K.f,{}),th=p.theme||(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'),z=Math.min(1.2,Math.max(1,+p.textScale||1));document.documentElement.dataset.theme=th;document.documentElement.style.setProperty('--text-scale',z)}
function cards(f='all'){let x=P.filter(p=>f==='all'||p.framework===f);$('#practiceGrid').innerHTML=x.map(p=>`<article class="practice-card"><span class="tag">${E(p.label)}</span><h2>${E(p.title)}</h2><p>${E(p.desc)}</p><span class="meta">${Math.ceil(p.duration/60)} min · guiada</span><button class="btn primary" data-practice-id="${p.id}">Abrir habilidade</button></article>`).join('');$$('[data-practice-id]',$('#practiceGrid')).forEach(b=>b.onclick=()=>open(b.dataset.practiceId))}
function choose(s){st=s;$$('.state-card').forEach(c=>c.setAttribute('aria-checked',String(c.dataset.state===s)));rec()}
function rec(){if(!st)return;let c=+$('#choiceSpace').value,i=+$('#intensity').value,id,why;if(c<=3){id='stop';why='Sua margem de escolha está baixa. Primeiro crie uma pausa comportamental e evite decisões no automático.'}else if(st==='mobilizado'&&i>=7){id='adiar';why='Há muita urgência. Separar “resolver depois” de “agir agora” costuma ser mais útil do que discutir com cada pensamento.'}else if(st==='mobilizado'){id='exalar';why='Há aceleração e alguma margem de escolha. Um recurso corporal simples pode reduzir velocidade sem exigir relaxamento.'}else if(st==='desligado'){id='movimento';why='Com baixa energia ou distanciamento, movimento pequeno e orientação externa tendem a ser mais toleráveis.'}else if(c>=6){id='valores';why='Já existe alguma estabilidade. Use essa margem para agir na direção do que importa, sem esperar a emoção desaparecer.'}else{id='orientar';why='Há algum espaço para observar; consolide presença antes de decidir.'}let p=P.find(x=>x.id===id);$('#recommendationTitle').textContent=p.title;$('#recommendationReason').textContent=why;$('#recommendationCard').innerHTML=`<h3>${E(p.title)}</h3><p>${E(p.desc)}</p>`;$('#startRecommended').dataset.practiceId=id;$('#recommendation').classList.remove('hidden')}
function open(id){a=P.find(p=>p.id===id);if(!a)return;stop();el=si=se=0;bi=+$('#intensity').value;bc=+$('#choiceSpace').value;$('#dialogCategory').textContent=a.label;$('#dialogTitle').textContent=a.title;$('#dialogIntro').textContent=a.intro;$('#practiceSafety').textContent=a.safety;$('#timer').textContent=T(a.duration);$('#practiceStartPause').textContent='Iniciar';$('#afterCheck').classList.add('hidden');$('#afterIntensity').value=bi;$('#afterIntensityValue').textContent=bi;$('#afterChoiceSpace').value=bc;$('#afterChoiceSpaceValue').textContent=bc;step();$('#practiceDialog').showModal()}
function step(){if(!a)return;let x=a.steps[si]||['Observe como está agora.',0];$('#guideStep').textContent=x[0];let v=$('#guideVisual');v.className='guide-visual'+(si%2?' pulse':'');if(voice)speak(x[0])}
function speak(x){if(!voice||!a)return;window.RC_AUDIO_N2?.play(a.id,si,x)}
function toggle(){if(!a)return;if(t){stop(false);$('#practiceStartPause').textContent='Continuar';return}$('#practiceStartPause').textContent='Pausar';t=setInterval(tick,1000)}
function tick(){el++;se++;let r=Math.max(0,a.duration-el);$('#timer').textContent=T(r);let x=a.steps[si];if(x&&se>=x[1]){si++;se=0;if(si<a.steps.length)step()}if(!r)finish()}
function finish(){stop();$('#practiceStartPause').textContent='Concluída';$('#guideStep').textContent='Observe a intensidade e sua margem de escolha agora.';$('#guideVisual').className='guide-visual';$('#afterCheck').classList.remove('hidden');if(voice)speak('Prática concluída. Observe a intensidade e sua margem de escolha agora.')}
function stop(c=true){if(t)clearInterval(t);t=null;if(c)window.RC_AUDIO_N2?.stop()}
function reset(){if(!a)return;stop();el=si=se=0;$('#timer').textContent=T(a.duration);$('#practiceStartPause').textContent='Iniciar';$('#afterCheck').classList.add('hidden');step()}
function save(){let ai=+$('#afterIntensity').value,ac=+$('#afterChoiceSpace').value,l=J(K.l,[]);l.unshift({id:crypto?.randomUUID?.()||Date.now(),at:new Date().toISOString(),practiceTitle:a.title,framework:a.framework,state:st||'',beforeIntensity:bi,afterIntensity:ai,beforeChoice:bc,afterChoice:ac,choiceDelta:ac-bc});localStorage.setItem(K.l,JSON.stringify(l.slice(0,120)));toast('Registro salvo somente neste dispositivo.');$('#practiceDialog').close();log()}
function log(){let l=J(K.l,[]),s=$('#logSummary'),v=$('#logList');if(!l.length){s.innerHTML='<div class="summary-card"><strong>0</strong><span>práticas registradas</span></div>';v.innerHTML='<p class="privacy-note">Nenhum registro salvo ainda.</p>';return}let d=l.filter(x=>x.afterIntensity<x.beforeIntensity).length,g=l.reduce((n,x)=>n+(x.choiceDelta||0),0)/l.length;s.innerHTML=`<div class="summary-card"><strong>${l.length}</strong><span>práticas registradas</span></div><div class="summary-card"><strong>${d}</strong><span>com menor intensidade</span></div><div class="summary-card"><strong>${g>0?'+':''}${g.toFixed(1)}</strong><span>ganho médio de escolha</span></div>`;v.innerHTML=l.slice(0,14).map(x=>`<article class="log-item"><div class="log-item-head"><h3>${E(x.practiceTitle)}</h3><span>${new Date(x.at).toLocaleDateString('pt-BR')}</span></div><p>Intensidade: ${x.beforeIntensity}/10 → ${x.afterIntensity}/10 · Escolha: ${x.beforeChoice}/10 → ${x.afterChoice}/10.</p></article>`).join('')}
function loadPlan(){let p=J(K.p,{});Object.entries(p).forEach(([k,v])=>{let e=document.getElementById(k);if(e&&typeof v==='string')e.value=v})}
function support(){let p=J(K.p,{}),q=[['1 · Vá para presença humana',p.supportPerson?`Procure ${E(p.supportPerson)} ou outra pessoa adulta de confiança.`:'Procure uma pessoa adulta de confiança e fique perto dela.'],['2 · Reduza decisões',p.anchorPhrase?`Use sua frase: “${E(p.anchorPhrase)}”`:'Adie decisões importantes. Foque no próximo passo seguro.'],['3 · Organize o ambiente',p.safePlace?`Se for seguro, vá para: ${E(p.safePlace)}.`:'Vá para um local previsível e próximo de pessoas confiáveis.'],['4 · Procure atendimento presencial','Se você não consegue permanecer seguro ou seus sintomas parecem uma emergência, procure atendimento presencial de urgência ou emergência.']];$('#supportPlanContent').innerHTML=q.map((x,i)=>`<div class="support-step"><strong>${x[0]}</strong><p>${x[1]}</p>${i===0&&p.supportContact?`<a href="tel:${encodeURIComponent(p.supportContact.replace(/[^+\d]/g,''))}">Ligar para contato salvo</a>`:''}</div>`).join('');$('#supportDialog').showModal()}
function saveWave(e){e.preventDefault();let d=Object.fromEntries(new FormData(e.currentTarget).entries()),w=J(K.w,[]);if(!Object.values(d).some(v=>String(v).trim()))return toast('Registre ao menos uma observação.');w.unshift({id:Date.now(),at:new Date().toISOString(),...d});localStorage.setItem(K.w,JSON.stringify(w.slice(0,40)));e.currentTarget.reset();waves();toast('Reflexão salva neste dispositivo.')}
function waves(){let w=J(K.w,[]),v=$('#afterWaveList');v.innerHTML=w.length?w.slice(0,10).map(x=>`<article class="log-item"><div class="log-item-head"><h3>Depois da onda</h3><span>${new Date(x.at).toLocaleDateString('pt-BR')}</span></div>${x.context?`<p><strong>Situação:</strong> ${E(x.context)}</p>`:''}${x.urge?`<p><strong>Urgência:</strong> ${E(x.urge)}</p>`:''}${x.skill?`<p><strong>Habilidade:</strong> ${E(x.skill)}</p>`:''}${x.earlier?`<p><strong>Perceber mais cedo:</strong> ${E(x.earlier)}</p>`:''}</article>`).join(''):'<p class="privacy-note">Nenhuma reflexão salva ainda.</p>'}
function exportAll(){let d={exportedAt:new Date().toISOString(),practices:J(K.l,[]),afterWave:J(K.w,[])};if(!d.practices.length&&!d.afterWave.length)return toast('Não há registros para exportar.');let b=new Blob([JSON.stringify(d,null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=`regulacao-em-crises-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function wire(){$$('.nav-item').forEach(b=>b.onclick=()=>route(b.dataset.route));$$('.state-card').forEach(c=>c.onclick=()=>choose(c.dataset.state));$('#intensity').oninput=e=>{$('#intensityValue').textContent=e.target.value;rec()};$('#choiceSpace').oninput=e=>{$('#choiceSpaceValue').textContent=e.target.value;rec()};$('#afterIntensity').oninput=e=>$('#afterIntensityValue').textContent=e.target.value;$('#afterChoiceSpace').oninput=e=>$('#afterChoiceSpaceValue').textContent=e.target.value;$('#startRecommended').onclick=e=>open(e.currentTarget.dataset.practiceId);$('#chooseOther').onclick=()=>route('praticas');$$('.chip').forEach(c=>c.onclick=()=>{$$('.chip').forEach(x=>x.classList.toggle('active',x===c));cards(c.dataset.filter)});$('#practiceStartPause').onclick=toggle;$('#practiceReset').onclick=reset;$('#repeatPractice').onclick=reset;$('#savePracticeResult').onclick=save;$('#voiceToggle').onclick=e=>{voice=!voice;e.currentTarget.setAttribute('aria-pressed',voice);e.currentTarget.textContent=`Áudio: ${voice?'ligado':'desligado'}`;if(!voice)window.RC_AUDIO_N2?.stop();if(voice&&a)speak($('#guideStep').textContent)};$('#practiceDialog').addEventListener('close',()=>stop());$('#personalPlanForm').onsubmit=e=>{e.preventDefault();localStorage.setItem(K.p,JSON.stringify(Object.fromEntries(new FormData(e.currentTarget).entries())));toast('Mapa salvo neste dispositivo.')};$('#clearPersonalPlan').onclick=()=>{if(confirm('Apagar seu mapa pessoal?')){localStorage.removeItem(K.p);$('#personalPlanForm').reset();toast('Mapa apagado.')}};$('#openSupportPlan').onclick=support;$('#afterWaveForm').onsubmit=saveWave;$('#clearAfterWave').onclick=()=>{if(confirm('Apagar reflexões?')){localStorage.removeItem(K.w);waves()}};$('#exportLog').onclick=exportAll;$('#clearLog').onclick=()=>{if(confirm('Apagar histórico de práticas?')){localStorage.removeItem(K.l);log()}};$('#themeBtn').onclick=()=>{let n=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=n;localStorage.setItem(K.f,JSON.stringify({...J(K.f,{}),theme:n}))};$('#textSizeBtn').onclick=()=>{let p=J(K.f,{}),n=(+p.textScale||1)>=1.2?1:Number(((+p.textScale||1)+.1).toFixed(1));document.documentElement.style.setProperty('--text-scale',n);localStorage.setItem(K.f,JSON.stringify({...p,textScale:n}));toast(n===1?'Texto padrão.':`Texto ${Math.round(n*100)}%.`)};addEventListener('beforeinstallprompt',e=>{e.preventDefault();install=e;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{if(!install)return;install.prompt();await install.userChoice;install=null;$('#installBtn').hidden=true}}
prefs();cards();loadPlan();log();waves();wire();if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js').catch(()=>{});
})();