(()=>{
'use strict';
const S={plan:'regulacaoPolivagal.plan.v1',log:'regulacaoPolivagal.log.v1',prefs:'regulacaoPolivagal.prefs.v1'};
const P=[
{id:'exalar',title:'Exalar um pouco mais longo',category:'mobilizado',label:'Para aceleração',duration:90,desc:'Respiração suave, sem retenção: inspire em 4 tempos e expire em 6, sempre de modo confortável.',intro:'Respire pequeno e confortável. Não há necessidade de encher totalmente os pulmões.',steps:[['Solte os ombros e perceba sua respiração como ela está.',10],['Inspire de forma leve por 4 tempos.',4,'expand'],['Expire de forma confortável por 6 tempos.',6],['Inspire leve por 4 tempos.',4,'expand'],['Expire confortável por 6 tempos.',6],['Continue no seu ritmo, deixando a saída do ar um pouco mais longa.',40,'pulse'],['Volte à respiração espontânea e observe o ambiente.',20]],safety:'Não faça força nem prenda o ar. Se houver tontura, falta de ar ou piora do desconforto, pare e respire normalmente.'},
{id:'orientar',title:'Orientação pelos sentidos',category:'mobilizado',label:'Para aceleração',duration:120,desc:'Usa visão, tato e audição para trazer atenção ao que está presente e concreto.',intro:'Você não precisa relaxar. Apenas permita que os sentidos coletem sinais do ambiente atual.',steps:[['Olhe lentamente para três objetos e note suas cores.',25],['Perceba três pontos de contato do corpo com cadeira, chão ou roupa.',25],['Identifique três sons próximos ou distantes.',25],['Escolha um objeto neutro e observe forma, textura ou tamanho.',25],['Pergunte: qual é a próxima ação pequena e segura que posso escolher?',20]],safety:'Se fechar os olhos aumentar desconforto, mantenha-os abertos. Prefira elementos neutros do ambiente.'},
{id:'pressao',title:'Pressão e apoio',category:'mobilizado',label:'Para aceleração',duration:75,desc:'Ajuda a perceber apoio físico real por meio dos pés, mãos e superfícies.',intro:'Use força moderada e confortável. O objetivo é notar apoio, não cansar o corpo.',steps:[['Apoie os dois pés no chão e perceba onde há mais pressão.',15],['Pressione os pés contra o chão e solte devagar.',15,'pulse'],['Una as palmas das mãos com pressão confortável e solte.',15,'pulse'],['Perceba costas, quadris ou braços sendo sustentados.',15],['Diminua a força e fique apenas com a sensação de apoio.',15]],safety:'Não use força que cause dor. Se houver lesão ou limitação física, escolha outra prática.'},
{id:'movimento',title:'Movimento pequeno e orientado',category:'desligado',label:'Para desligamento',duration:100,desc:'Recupera presença com movimentos leves e graduais, sem exigir grande energia.',intro:'Comece menor do que acha necessário. O objetivo é aumentar um pouco o contato com corpo e ambiente.',steps:[['Mova lentamente os dedos das mãos e observe a sensação.',20],['Empurre suavemente os pés contra o chão e perceba as pernas.',20,'pulse'],['Gire os ombros ou mova o pescoço dentro do confortável.',20],['Olhe para a esquerda e para a direita, encontrando algo familiar.',20],['Escolha uma ação simples: água, postura ou proximidade de alguém.',20]],safety:'Evite movimentos rápidos se estiver tonto, fraco ou com dor. Faça sentado se for mais seguro.'},
{id:'temperatura-neutra',title:'Contraste suave de temperatura',category:'desligado',label:'Para desligamento',duration:70,desc:'Usa uma temperatura confortável para tornar a experiência sensorial mais nítida.',intro:'Escolha apenas uma temperatura confortável, nunca extrema.',steps:[['Segure um objeto fresco ou morno e perceba a temperatura.',20],['Descreva mentalmente: fresco, neutro ou morno.',15],['Troque o objeto de mão e observe se a sensação muda.',15],['Olhe ao redor e nomeie onde você está e o que fará em seguida.',20]],safety:'Não use gelo diretamente na pele, água muito fria, calor intenso ou qualquer técnica que cause dor.'},
{id:'voz',title:'Som suave e expiração',category:'estavel',label:'Para estabilizar',duration:90,desc:'Combina expiração confortável com som baixo, se isso for agradável.',intro:'O som é opcional e funciona apenas como pista de ritmo e presença.',steps:[['Respire normalmente por alguns segundos.',15],['Na próxima expiração, solte um som baixo e confortável, como “mmm”.',20,'pulse'],['Repita apenas se for agradável.',20,'pulse'],['Pare o som e perceba garganta, face, peito e ambiente.',20],['Retorne à respiração espontânea.',15]],safety:'Se o som incomodar, pule esta parte e apenas expire normalmente.'},
{id:'conexao',title:'Conexão segura',category:'estavel',label:'Para estabilizar',duration:80,desc:'Organiza uma ação de contato humano simples e proporcional ao momento.',intro:'Pense em alguém previsível, respeitoso e seguro para você.',steps:[['Lembre de uma pessoa com quem você não precisa explicar tudo.',20],['Pense em uma frase simples: “Você pode ficar comigo alguns minutos?”',20],['Escolha o canal mais simples: presença, ligação ou mensagem.',20],['Decida apenas a próxima ação. O restante pode esperar.',20]],safety:'Procure pessoas que respeitem seus limites. Se alguém aumenta seu medo ou pressão, escolha outro apoio.'},
{id:'frase',title:'Nomear sem discutir com a emoção',category:'estavel',label:'Para estabilizar',duration:75,desc:'Separa sensação, interpretação e escolha sem exigir que o pensamento desapareça.',intro:'A meta não é provar que o pensamento está errado. É ganhar espaço antes de agir.',steps:[['Meu corpo está percebendo ameaça ou sobrecarga.',15],['Minha mente está dizendo que preciso resolver isso agora.',20],['Posso sentir isso sem decidir tudo neste minuto.',20],['Escolha uma ação pequena, reversível e segura.',20]],safety:'Adapte as frases à sua experiência. A prática deve aumentar clareza, não invalidar o que você sente.'}
];
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const json=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??d}catch{return d}}, esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state=null,active=null,timer=null,elapsed=0,step=0,stepElapsed=0,before=5,voice=false,installPrompt=null;
function route(r){$$('.view').forEach(v=>v.classList.toggle('active',v.dataset.view===r));$$('.nav-item').forEach(b=>{let a=b.dataset.route===r;b.classList.toggle('active',a);a?b.setAttribute('aria-current','page'):b.removeAttribute('aria-current')});window.scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});if(r==='mapa')renderLog()}
function toast(t){let e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2200)}
function pref(p){let x={...json(S.prefs,{}),...p};localStorage.setItem(S.prefs,JSON.stringify(x));return x}
function applyPrefs(){let p=json(S.prefs,{}),theme=p.theme||(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'),scale=Math.min(1.2,Math.max(1,Number(p.textScale||1)));document.documentElement.dataset.theme=theme;document.documentElement.style.setProperty('--text-scale',scale)}
function cards(filter='all'){let list=P.filter(p=>filter==='all'||p.category===filter);$('#practiceGrid').innerHTML=list.map(p=>`<article class="practice-card"><span class="tag">${esc(p.label)}</span><h2>${esc(p.title)}</h2><p>${esc(p.desc)}</p><span class="meta">${Math.ceil(p.duration/60)} min · guiada · pode parar a qualquer momento</span><button class="btn primary" type="button" data-practice-id="${p.id}">Abrir prática</button></article>`).join('');$$('[data-practice-id]',$('#practiceGrid')).forEach(b=>b.onclick=()=>openPractice(b.dataset.practiceId))}
function choose(s){state=s;$$('.state-card').forEach(c=>c.setAttribute('aria-checked',String(c.dataset.state===s)));let id={mobilizado:'exalar',desligado:'movimento',estavel:'orientar'}[s],p=P.find(x=>x.id===id),reason={mobilizado:'Quando há muita aceleração, reduzir o ritmo de forma suave pode ampliar margem de escolha.',desligado:'Quando há pouca energia ou contato, movimentos pequenos podem ser mais toleráveis do que exigir relaxamento.',estavel:'Como já existe alguma margem de escolha, uma prática de orientação pode consolidar presença antes do próximo passo.'}[s];$('#recommendationTitle').textContent=p.title;$('#recommendationReason').textContent=reason;$('#recommendationCard').innerHTML=`<h3>${esc(p.title)}</h3><p>${esc(p.desc)}</p>`;$('#startRecommended').dataset.practiceId=p.id;$('#recommendation').classList.remove('hidden');$('#recommendation').scrollIntoView({behavior:'smooth',block:'center'})}
function openPractice(id){active=P.find(p=>p.id===id);if(!active)return;stop();elapsed=step=stepElapsed=0;before=Number($('#intensity').value||5);$('#dialogCategory').textContent=active.label;$('#dialogTitle').textContent=active.title;$('#dialogIntro').textContent=active.intro;$('#practiceSafety').textContent=active.safety;$('#timer').textContent=time(active.duration);$('#practiceStartPause').textContent='Iniciar';$('#afterCheck').classList.add('hidden');$('#afterIntensity').value=before;$('#afterIntensityValue').textContent=before;renderStep();$('#practiceDialog').showModal()}
function renderStep(){if(!active)return;let x=active.steps[step]||['Observe como você está agora.',0];$('#guideStep').textContent=x[0];let v=$('#guideVisual');v.className='guide-visual';if(x[2]==='expand')v.classList.add('expand');if(x[2]==='pulse')v.classList.add('pulse');if(voice)speak(x[0])}
function speak(t){if(!voice||!('speechSynthesis'in window))return;speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(t);u.lang='pt-BR';u.rate=.88;speechSynthesis.speak(u)}
function toggle(){if(!active)return;if(timer){stop(false);$('#practiceStartPause').textContent='Continuar';return}$('#practiceStartPause').textContent='Pausar';timer=setInterval(tick,1000)}
function tick(){elapsed++;stepElapsed++;let rem=Math.max(0,active.duration-elapsed);$('#timer').textContent=time(rem);let x=active.steps[step];if(x&&stepElapsed>=x[1]){step++;stepElapsed=0;if(step<active.steps.length)renderStep()}if(rem<=0)finish()}
function finish(){stop();$('#practiceStartPause').textContent='Concluída';$('#guideStep').textContent='Prática concluída. Observe o que mudou — mesmo que tenha sido pouco ou nada.';$('#guideVisual').className='guide-visual';$('#afterCheck').classList.remove('hidden');if(voice)speak('Prática concluída. Observe como você está agora.')}
function stop(cancel=true){if(timer)clearInterval(timer);timer=null;if(cancel&&'speechSynthesis'in window)speechSynthesis.cancel()}
function reset(){if(!active)return;stop();elapsed=step=stepElapsed=0;$('#timer').textContent=time(active.duration);$('#practiceStartPause').textContent='Iniciar';$('#afterCheck').classList.add('hidden');renderStep()}
const time=s=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;
function saveResult(){let after=Number($('#afterIntensity').value||before),log=json(S.log,[]);log.unshift({id:globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random()}`,at:new Date().toISOString(),practiceId:active.id,practiceTitle:active.title,state:state||active.category,before,after,delta:after-before});localStorage.setItem(S.log,JSON.stringify(log.slice(0,100)));toast('Resultado salvo somente neste dispositivo.');$('#practiceDialog').close();renderLog()}
function renderLog(){let log=json(S.log,[]),sum=$('#logSummary'),list=$('#logList');if(!log.length){sum.innerHTML='<div class="summary-card"><strong>0</strong><span>práticas registradas</span></div>';list.innerHTML='<p class="privacy-note">Nenhum registro salvo ainda.</p>';return}let improved=log.filter(x=>x.after<x.before).length,avg=log.reduce((a,x)=>a+x.after-x.before,0)/log.length;sum.innerHTML=`<div class="summary-card"><strong>${log.length}</strong><span>práticas registradas</span></div><div class="summary-card"><strong>${improved}</strong><span>com redução percebida</span></div><div class="summary-card"><strong>${avg>0?'+':''}${avg.toFixed(1)}</strong><span>mudança média</span></div>`;list.innerHTML=log.slice(0,12).map(x=>`<article class="log-item"><div class="log-item-head"><h3>${esc(x.practiceTitle)}</h3><span>${new Date(x.at).toLocaleDateString('pt-BR')}</span></div><p>Intensidade: ${x.before}/10 → ${x.after}/10 (${x.after-x.before>0?'+':''}${x.after-x.before}).</p></article>`).join('')}
function loadPlan(){let p=json(S.plan,{});Object.entries(p).forEach(([k,v])=>{let e=document.getElementById(k);if(e&&typeof v==='string')e.value=v})}
function savePlan(e){e.preventDefault();localStorage.setItem(S.plan,JSON.stringify(Object.fromEntries(new FormData(e.currentTarget).entries())));toast('Plano salvo somente neste dispositivo.')}
function support(){let p=json(S.plan,{}),parts=[['1 · Vá para presença humana',p.supportPerson?`Procure ${esc(p.supportPerson)} ou outra pessoa adulta de confiança.`:'Procure uma pessoa adulta de confiança e fique perto dela.'],['2 · Reduza a tarefa',p.anchorPhrase?`Use sua frase: “${esc(p.anchorPhrase)}”`:'Adie decisões importantes. Foque apenas no próximo passo seguro e simples.'],['3 · Organize o ambiente',p.safePlace?`Se for seguro, vá para: ${esc(p.safePlace)}.`:'Vá para um local previsível, com menos estímulos e próximo de pessoas confiáveis.'],['4 · Procure atendimento presencial','Se você não consegue se manter seguro ou os sintomas estão intensos, procure atendimento presencial de urgência ou emergência na sua região.']];$('#supportPlanContent').innerHTML=parts.map((x,i)=>`<div class="support-step"><strong>${x[0]}</strong><p>${x[1]}</p>${i===0&&p.supportContact?`<a href="tel:${encodeURIComponent(p.supportContact.replace(/[^+\d]/g,''))}">Ligar para contato salvo</a>`:''}</div>`).join('');$('#supportDialog').showModal()}
function exportLog(){let log=json(S.log,[]);if(!log.length)return toast('Não há registros para exportar.');let blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),records:log},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`regulacao-polivagal-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function wire(){ $$('.nav-item').forEach(b=>b.onclick=()=>route(b.dataset.route));$$('.state-card').forEach(c=>c.onclick=()=>choose(c.dataset.state));$('#intensity').oninput=e=>$('#intensityValue').textContent=e.target.value;$('#afterIntensity').oninput=e=>$('#afterIntensityValue').textContent=e.target.value;$('#startRecommended').onclick=e=>openPractice(e.currentTarget.dataset.practiceId);$('#chooseOther').onclick=()=>route('praticas');$$('.chip').forEach(c=>c.onclick=()=>{$$('.chip').forEach(x=>x.classList.toggle('active',x===c));cards(c.dataset.filter)});$('#practiceStartPause').onclick=toggle;$('#practiceReset').onclick=reset;$('#repeatPractice').onclick=reset;$('#savePracticeResult').onclick=saveResult;$('#voiceToggle').onclick=e=>{voice=!voice;e.currentTarget.setAttribute('aria-pressed',voice);e.currentTarget.textContent=`Voz: ${voice?'ligada':'desligada'}`;if(!voice&&'speechSynthesis'in window)speechSynthesis.cancel();if(voice&&active)speak($('#guideStep').textContent)};$('#practiceDialog').addEventListener('close',()=>stop());$('#personalPlanForm').onsubmit=savePlan;$('#clearPersonalPlan').onclick=()=>{if(confirm('Apagar seu mapa pessoal salvo neste navegador?')){localStorage.removeItem(S.plan);$('#personalPlanForm').reset();toast('Dados locais apagados.')}};$('#openSupportPlan').onclick=support;$('#exportLog').onclick=exportLog;$('#clearLog').onclick=()=>{if(confirm('Apagar todo o histórico salvo neste navegador?')){localStorage.removeItem(S.log);renderLog();toast('Histórico apagado.')}};$('#themeBtn').onclick=()=>{let next=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=next;pref({theme:next})};$('#textSizeBtn').onclick=()=>{let cur=Number(json(S.prefs,{}).textScale||1),next=cur>=1.2?1:Number((cur+.1).toFixed(1));document.documentElement.style.setProperty('--text-scale',next);pref({textScale:next});toast(next===1?'Tamanho de texto padrão.':`Texto ampliado para ${Math.round(next*100)}%.`)};window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{if(!installPrompt)return;installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$('#installBtn').hidden=true}}
applyPrefs();cards();loadPlan();renderLog();wire();if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js').catch(()=>{});
})();
